name: Build
on: [push]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: yarn
            - name: Build
              run: yarn build
