name: Lint
on: [push]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: yarn
            - name: Check prettier doesn't find any changes
              run: yarn prettier . --check
